add_newline = false

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[git_branch]
symbol = ''

[git_status]
format = '([$all_status$ahead_behind]($style) )'
stashed = ''
untracked = '✘'
modified = '✘'
staged = '✘'
renamed = '✘'
deleted = '✘'
